services:
  app:
    build:
      dockerfile: Dockerfile
      context: .
    env_file:
      - cmd/auction/.env
    network_mode: host

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
